name: Meu Workflow Simples
on:
  schedule:
    - cron: "5 23 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello, World!"
